//const chroma = require("chroma-js");

export default (tokens: Record<string, any>) => ({
  "terminal.foreground": "#c4c8c6",
  "terminal.selectionBackground": "#6f734340",
  "terminalCursor.background": "#0087FF",
  "terminalCursor.foreground": "#e6e6e6",
  "terminal.border": "#80808059",
  "terminal.ansiBlack": "#000000",
  "terminal.ansiBlue": "#4965a1",
  "terminal.ansiBrightBlack": "#4d4d4d",
  "terminal.ansiBrightBlue": "#5c86e0",
  "terminal.ansiBrightCyan": "#7fe0d3",
  "terminal.ansiBrightGreen": "#5ac220",
  "terminal.ansiBrightMagenta": "#dd8bea",
  "terminal.ansiBrightRed": "#e03c3c",
  "terminal.ansiBrightWhite": "#e5e5e5",
  "terminal.ansiBrightYellow": "#ffdbad",
  "terminal.ansiCyan": "#70aea6",
  "terminal.ansiGreen": "#51902e",
  "terminal.ansiMagenta": "#b792bd",
  "terminal.ansiRed": "#d35656",
  "terminal.ansiWhite": "#c4c8c6",
  "terminal.ansiYellow": "#f8c465",
});
